version: '3.8'

services:
  rest-app:
    build:
      dockerfile: Dockerfile
      context: .
      # target: development
    volumes:
      - .:/src
    env_file:
      - .development.env

    command: npm run start:dev
    ports:
      - 4000:4000
    